import { Link } from "react-router-dom";
import { ArrowLeft, Scale, FileCheck, AlertTriangle, Gavel, UserCheck, MessageSquare } from "lucide-react";
import PageHero from "@/components/PageHero";
import AnimatedSection from "@/components/AnimatedSection";

const sections = [
  {
    icon: FileCheck,
    title: "Services & Scope",
    content:
      "Cryst Bio Solutions Pvt. Ltd. agrees to provide preclinical research, toxicology testing, biocompatibility evaluation, histopathology, microbiology analysis, and laboratory animal supply services as mutually agreed upon in individual study agreements or service contracts. All services are performed in accordance with applicable regulatory standards including OECD guidelines, ISO 10993, GLP principles, and CPCSEA requirements as specified in each study protocol.",
  },
  {
    icon: Scale,
    title: "Intellectual Property",
    content:
      "All study data, results, and reports generated by Cryst Bio Solutions Pvt. Ltd. during the course of a commissioned study shall be the property of the client upon full payment. Cryst Bio Solutions Pvt. Ltd. retains the right to use anonymized, aggregate data for internal quality improvement and regulatory compliance purposes. Our methodologies, standard operating procedures (SOPs), and proprietary testing protocols remain our intellectual property.",
  },
  {
    icon: AlertTriangle,
    title: "Limitation of Liability",
    content:
      "Cryst Bio Solutions Pvt. Ltd.'s liability for any claim arising from our services shall be limited to the total fees paid for the specific study giving rise to the claim. We shall not be liable for any indirect, incidental, special, consequential, or punitive damages, including but not limited to loss of profits, data, or business opportunities, even if advised of the possibility of such damages. This limitation does not apply to liability that cannot be excluded under applicable law.",
  },
  {
    icon: Gavel,
    title: "Governing Law",
    content:
      "These terms shall be governed by and construed in accordance with the laws of India. Any disputes arising from these terms shall be subject to the exclusive jurisdiction of the courts in Pune, Maharashtra, India. The parties agree to attempt to resolve any dispute through good-faith negotiations before pursuing legal remedies.",
  },
  {
    icon: UserCheck,
    title: "Client Responsibilities",
    content:
      "Clients are responsible for providing accurate and complete information about the test substances, study requirements, and regulatory context. Clients must ensure they have all necessary rights and approvals for the materials submitted for testing. Clients shall not use any test results or reports in a manner that is false, misleading, or violates any applicable regulations.",
  },
  {
    icon: MessageSquare,
    title: "Confidentiality",
    content:
      "Both parties agree to maintain strict confidentiality regarding all proprietary information, study data, and business details shared during the course of their engagement. Confidentiality obligations shall survive the termination of any service agreement for a period of five (5) years. This section does not apply to information that is or becomes publicly available through no fault of the receiving party.",
  },
];

const TermsOfService = () => (
  <div>
    <PageHero
      title="Terms of Service"
      subtitle="Terms and conditions governing the use of our website and services."
      breadcrumb="Terms of Service"
    />

    <section className="section-padding relative overflow-hidden">
      <div className="container mx-auto px-4 relative z-10 max-w-4xl">
        <AnimatedSection>
          <div className="glass-card p-8 md:p-12 rounded-2xl space-y-8">
            <p className="text-muted-foreground leading-relaxed">
              <strong className="text-foreground">Last Updated:</strong> June 2026
            </p>

            <p className="text-muted-foreground leading-relaxed">
              Welcome to the Cryst Bio Solutions Pvt. Ltd. website. By accessing
              or using our website and services, you agree to comply with and be
              bound by the following terms and conditions. Please read them
              carefully.
            </p>

            <div className="space-y-10">
              {sections.map((section, i) => (
                <div key={section.title} className="space-y-4">
                  <div className="flex items-center gap-3">
                    <div className="w-10 h-10 rounded-xl bg-primary/10 border border-primary/20 flex items-center justify-center shrink-0">
                      <section.icon className="w-5 h-5 text-primary" />
                    </div>
                    <h2 className="text-xl font-bold font-display text-foreground">
                      {i + 1}. {section.title}
                    </h2>
                  </div>
                  <p className="text-muted-foreground leading-relaxed pl-[3.25rem]">
                    {section.content}
                  </p>
                </div>
              ))}
            </div>

            <div className="pt-6 border-t border-border/50">
              <h3 className="text-lg font-bold font-display text-foreground mb-3">
                Contact for Legal Inquiries
              </h3>
              <p className="text-muted-foreground leading-relaxed">
                For legal inquiries or questions regarding these terms, please
                contact us at:
              </p>
              <ul className="mt-3 space-y-2 text-muted-foreground">
                <li>
                  <strong className="text-foreground">Email:</strong>{" "}
                  <a href="mailto:info@crystbio.com" className="text-primary hover:underline">
                    info@crystbio.com
                  </a>
                </li>
                <li>
                  <strong className="text-foreground">Phone:</strong>{" "}
                  <a href="tel:+917276361762" className="text-primary hover:underline">
                    +91 7276361762
                  </a>
                </li>
                <li>
                  <strong className="text-foreground">Address:</strong>{" "}
                  Cryst Bio Solutions Pvt. Ltd., Pune, Maharashtra, India
                </li>
              </ul>
            </div>
          </div>
        </AnimatedSection>

        <div className="mt-10 text-center">
          <Link
            to="/contact"
            className="inline-flex items-center gap-2 text-primary hover:underline font-medium"
          >
            <ArrowLeft className="w-4 h-4" /> Back to Contact
          </Link>
        </div>
      </div>
    </section>
  </div>
);

export default TermsOfService;
